spring:
  application:
    name: zuul


eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
server:
  port: 8861

#zuul:
#  routes:
#    test:
#      path: /test/**
#      service
