---
spring:
  profiles: peer1
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
